<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrdersSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('orders')->insert([
            [
                'user_id' => 1,
                'status' => '0',
                'notes' => 'توصيل سريع',
                'address' => 'Damascus, Syria',
                'x' => '33.5138',
                'y' => '36.2765',
                'price' => 100.00,
                'delivery_price' => 5.00,
                'coupon_id' => null,
                'discount' => null,
                'total_price' => 105.00,
                'payment_method' => 'cash',
                'is_paid' => '0',
                'cart_count' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'status' => '1',
                'notes' => 'من فضلك ضع الأكياس على الباب',
                'address' => 'Aleppo, Syria',
                'x' => '36.2021',
                'y' => '37.1343',
                'price' => 150.00,
                'delivery_price' => 7.00,
                'coupon_id' => null,
                'discount' => null,
                'total_price' => 157.00,
                'payment_method' => 'card',
                'is_paid' => '0',
                'cart_count' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'status' => '0',
                'notes' => 'بدون بصل رجاءً',
                'address' => 'Homs, Syria',
                'x' => '34.7306',
                'y' => '36.7094',
                'price' => 200.00,
                'delivery_price' => 5.00,
                'coupon_id' => null,
                'discount' => null,
                'total_price' => 205.00,
                'payment_method' => 'cash',
                'is_paid' => '0',
                'cart_count' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'status' => '2',
                'notes' => 'اتصل قبل الوصول',
                'address' => 'Latakia, Syria',
                'x' => '35.5196',
                'y' => '35.7906',
                'price' => 180.00,
                'delivery_price' => 6.00,
                'coupon_id' => null,
                'discount' => null,
                'total_price' => 186.00,
                'payment_method' => 'card',
                'is_paid' => '0',
                'cart_count' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'status' => '1',
                'notes' => 'شوية كاتشب زيادة',
                'address' => 'Tartous, Syria',
                'x' => '34.8890',
                'y' => '35.8866',
                'price' => 90.00,
                'delivery_price' => 4.00,
                'coupon_id' => null,
                'discount' => null,
                'total_price' => 94.00,
                'payment_method' => 'cash',
                'is_paid' => '0',
                'cart_count' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'status' => '0',
                'notes' => 'توصيل للجامعة',
                'address' => 'Damascus University',
                'x' => '33.5120',
                'y' => '36.2988',
                'price' => 120.00,
                'delivery_price' => 5.00,
                'coupon_id' => null,
                'discount' => null,
                'total_price' => 125.00,
                'payment_method' => 'card',
                'is_paid' => '0',
                'cart_count' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            
        ]);
    }
}
